import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#f7f9fb",
        surface: "#f7f9fb",
        "surface-variant": "#d9e4ea",
        "surface-dim": "#cfdce3",
        "surface-bright": "#f7f9fb",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f0f4f7",
        "surface-container": "#e8eff3",
        "surface-container-high": "#e1e9ee",
        "surface-container-highest": "#d9e4ea",
        outline: "#717c82",
        "outline-variant": "#a9b4b9",
        primary: "#494bd6",
        "primary-dim": "#3c3dca",
        "primary-container": "#e1e0ff",
        "primary-fixed": "#e1e0ff",
        "primary-fixed-dim": "#d1d0ff",
        "on-primary": "#faf6ff",
        "on-primary-container": "#3b3cc9",
        "on-primary-fixed": "#2622b7",
        "on-primary-fixed-variant": "#4647d3",
        secondary: "#545f74",
        "secondary-dim": "#485367",
        "secondary-container": "#d8e3fb",
        "secondary-fixed": "#d8e3fb",
        "secondary-fixed-dim": "#cad5ed",
        "on-secondary": "#f8f8ff",
        "on-secondary-container": "#475266",
        "on-secondary-fixed": "#354053",
        "on-secondary-fixed-variant": "#515c70",
        tertiary: "#605c78",
        "tertiary-dim": "#54506b",
        "tertiary-container": "#e3dbfd",
        "tertiary-fixed": "#e3dbfd",
        "tertiary-fixed-dim": "#d4cdee",
        "on-tertiary": "#fcf7ff",
        "on-tertiary-container": "#514d68",
        "on-tertiary-fixed": "#3e3a54",
        "on-tertiary-fixed-variant": "#5b5672",
        "on-surface": "#2a3439",
        "on-surface-variant": "#566166",
        "on-background": "#2a3439",
        error: "#9f403d",
        "error-dim": "#4e0309",
        "error-container": "#fe8983",
        "on-error": "#fff7f6",
        "on-error-container": "#752121",
        "inverse-surface": "#0b0f10",
        "inverse-on-surface": "#9a9d9f",
        "inverse-primary": "#8083ff",
        "surface-tint": "#494bd6",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["Manrope", "ui-sans-serif", "system-ui", "sans-serif"],
        body: ["Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        label: ["Inter", "ui-sans-serif", "system-ui", "sans-serif"],
      },
      boxShadow: {
        ambient: "0px 10px 40px rgba(42, 52, 57, 0.06)",
      },
    },
  },
  plugins: [],
};
export default config;
